[package]
name = "markemptydirs-rs"
version = "0.1.0"
authors = ["Jonny Dee <jonny.dee@gmx.net>"]

[dependencies.api]
path = "libs/api"

[dependencies.cli]
path = "libs/cli"

[dependencies]
clap = "*"
std-logger = "*"
