[package]
name = "markemptydirs"
version = "0.1.0"
authors = ["Johann Duscher <jonny.dee@posteo.net>"]

[dependencies.api]
path = "libs/api"

[dependencies.cli]
path = "libs/cli"

[dependencies]
clap = "*"
std-logger = "*"
